name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup UV
        uses: astral-sh/setup-uv@v6

      - name: Setup Python
        run: uv python install ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --dev

      - name: Run Linting
        run: uv run ruff check .

      - name: Run Type Checking
        run: uv run mypy src

      - name: Run Unit Tests
        run: uv run pytest -v

      - name: Test Package Build
        run: uv build